export let foodList = [
  { id:'1' , name: 'Burger', description: 'A burger, short for hamburger, is a popular food item consisting of a cooked patty made from ground meat, typically beef,although other meats or plant-based alternatives can also be used. The patty is usually seasoned with various spices and grilled, fried, or broiled to achieve the desired level of doneness. It is then placed between two halves of a bun, which can be toasted or left as is. Burgers often come with a variety of toppings and condiments, such as lettuce, tomato, onions, pickles, cheese, ketchup, mustard, mayonnaise, and more. These toppings can be customized based on personal preference, allowing for a wide range of flavor combinations. Some burgers may also include additional ingredients like bacon, mushrooms, avocado, or special sauces to enhance the taste. Burgers are commonly served with side dishes like french fries, onion rings, coleslaw, or a salad. They are enjoyed by people of all ages and are a staple in many fast-food restaurants, diners, and backyard barbecues.', href: '/products/', pic:'../images/burger.png'
  , attribute: "Burger" },
  
  { id:'2', name: 'Bacon Burger', description: 'A bacon burger is a type of burger that includes bacon as one of its main ingredients. It typically consists of a beef patty, cooked to desired doneness, topped with crispy bacon strips. The bacon adds a smoky and savory flavor to the burger, complementing the beef. Additional toppings such as cheese, lettuce, tomato, onions, and condiments like ketchup or mayonnaise can be added based on personal preference. The burger is usually served on a bun and can be enjoyed with a side of fries or a salad.', href: '/products/', pic:'../images/bacon.png'
  , attribute: "Bacon" },

  { id:'3', name: 'Chicken Burger', description: 'A chicken burger is a type of burger that features a chicken patty as the main ingredient instead of beef. The patty is typically made from ground or minced chicken meat, which is seasoned with various herbs, spices, and sometimes breadcrumbs to enhance its flavor and texture. The chicken patty is usually cooked by grilling, frying, or baking until it reaches a safe internal temperature. It is then placed between two halves of a bun, similar to a traditional burger. Chicken burgers can be customized with a variety of toppings and condiments, such as lettuce, tomato, onions, pickles, cheese, mayonnaise, mustard, barbecue sauce, or any other preferred additions. These toppings can be adjusted to suit personal taste preferences. Chicken burgers are a popular alternative to beef burgers, offering a lighter and leaner option. They are commonly found on menus at fast-food chains, restaurants, and food trucks. They can be served with a side of fries, coleslaw, or a salad to complete the meal.', href: '/products/', pic:'../images/chicken-burger.png'
  , attribute: "Chicken-Burger" },

  { id:'4', name: 'Chicken Strips', description: 'Chicken strips, also known as chicken tenders or chicken fingers, are a popular food item made from boneless, skinless chicken breast meat. They are typically cut into long, thin strips or fingers, hence the name. To prepare chicken strips, the chicken breast is usually sliced into uniform pieces. The chicken strips are then coated in a seasoned breading or batter, which can include a mixture of flour, breadcrumbs, herbs, and spices. This coating helps to provide a crispy and flavorful outer layer when cooked. Chicken strips can be cooked in various ways, including deep-frying, baking, or pan-frying. Deep-frying is a common method that results in a crispy and golden exterior, while baking or pan-frying can provide a healthier alternative with less oil. Chicken strips are often served as a standalone dish or as part of a meal. They can be enjoyed with a variety of dipping sauces, such as ketchup, barbecue sauce, honey mustard, or ranch dressing. They are a popular choice for appetizers, snacks, or as a main course for both children and adults.', href: '/products/', pic:'../images/chicken-strip.png'
  , attribute: "Chicken-Strips" },

  { id:'5', name: 'Salmon', description: 'Salmon is a type of fish that is highly valued for its flavor, nutritional benefits, and versatility in cooking. It is a species of fish that is native to both freshwater and saltwater environments, and it is known for its distinctive pink flesh. Salmon is rich in omega-3 fatty acids, high-quality protein, and various vitamins and minerals, making it a nutritious choice. It can be prepared in various ways, including grilling, baking, broiling, or pan-searing. The cooking method chosen can depend on personal preference and desired flavoWhen cooked, salmon has a tender and flaky texture with a rich, buttery taste. It pairs well with a wide range of flavors and ingredients, such as lemon, dill, garlic, soy sauce, or honey. It can be served as a main dish alongside vegetables, rice, or potatoes, or it can be used in salads, sandwiches, or sushi.Salmon is not only enjoyed for its taste but also recognized for its health benefits. It is a good source of omega-3 fatty acids, which are known to support heart health and brain function. It is also a good source of protein, which is essential for muscle growth and repair.Overall, salmon is a versatile and nutritious fish that is appreciated for its delicious taste and health benefits.', href: '/products/', pic:'../images/salmon.png'
  , attribute: "Salmon" },

  { id:'6', name: 'Shrimp Taco', description: 'A shrimp taco is a type of taco that features shrimp as the main protein. It is a popular dish in Mexican and seafood cuisine. To make a shrimp taco, shrimp is typically seasoned with a combination of spices such as chili powder, cumin, garlic, and lime juice. The shrimp can be grilled, sautéed, or fried until cooked through and slightly caramelized. The cooked shrimp is then placed in a tortilla, which is a soft, folded corn or flour-based flatbread. The tortilla can be warmed or toasted before filling. Shrimp tacos are often accompanied by various toppings and garnishes to enhance the flavors and textures. Common toppings include shredded lettuce, diced tomatoes, sliced avocado, chopped onions, cilantro, and a squeeze of lime juice. Additional condiments such as salsa, sour cream, or a spicy sauce like chipotle mayo can be added for extra flavor. Shrimp tacos are known for their combination of savory, tangy, and fresh flavors. They are a versatile dish that can be enjoyed as a light meal or as part of a larger Mexican-inspired feast.', href: '/products/', pic:'../images/shrimp-taco.png'
  , attribute: "Shrimp-Taco" },

  { id:'7', name: 'Steak', description: 'Steak is a type of meat that is typically cut from beef, although it can also be sourced from other animals such as pork, lamb, or veal. It is known for its tenderness and rich flavor. Steak is usually obtained from the muscles of the animal, which are often well-exercised and contain a higher amount of protein. It is commonly cooked by grilling, broiling, or pan-searing to achieve the desired level of doneness, ranging from rare to well-done. Steak is a popular choice for many meat lovers and is often served as a main course in various cuisines around the world.', href: '/products/', pic:'../images/steak.png'
  , attribute: "Steak" },

  { id:'8', name: 'Taco', description: 'A taco is a traditional Mexican dish that consists of a tortilla, which is a thin, flatbread made from corn or wheat flour. The tortilla is typically folded or rolled and filled with various ingredients. The most common filling for a taco is seasoned meat, such as beef, chicken, or pork. However, there are also vegetarian options available, with fillings like beans, cheese, or grilled vegetables. Tacos are often garnished with toppings like lettuce, tomatoes, onions, salsa, guacamole, or sour cream to add flavor and texture. They are enjoyed as a handheld food and can be customized to individual preferences. Tacos are popular worldwide and are often served in Mexican restaurants or as street food.', href: '/products/', pic:'../images/taco.png'
  , attribute: "Taco" },

  { id:'9',name: 'Wings', description: 'Chicken wings are a popular appetizer or main dish made from the wings of chickens. They are typically prepared by separating the wings into two sections, the drum and the flat, and discarding the wingtip. The wings are then seasoned, marinated, or coated in various sauces or spices before being cooked. Common cooking methods for chicken wings include frying, baking, grilling, or even air frying. Chicken wings are known for their tender and juicy meat, and they have a unique combination of crispy skin and flavorful meat. They can be enjoyed with a variety of dipping sauces, such as buffalo sauce, barbecue sauce, teriyaki sauce, or honey mustard. Chicken wings are often served as a finger food at parties, sports events, or as a popular menu item in restaurants specializing in wings. They come in different flavors and heat levels, allowing individuals to choose their preferred level of spiciness.', href: '/products/', pic:'../images/wings.png'
  , attribute: "Wings" },

];